create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table MEDECIN (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table MEDECIN add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UK4r9utyfp595dnepdpjl6a7rr0 unique (MEDNO);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, service_SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Medecin_Service (Medecin_MEDNO integer not null, serviceDirige_SERVNO integer not null) engine=InnoDB;
create table Service (SERVNO integer not null auto_increment, dirigePar_MEDNO integer, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
create table Service_Medecin (Service_SERVNO integer not null, medecins_MEDNO integer not null) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKmf27fmpdqjkv256vqst0rs1r9 foreign key (service_SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKpepj2nxfefejmp1gchjmqv5l7 foreign key (serviceDirige_SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKb159t3r8h38x92trx1r0jwd9k foreign key (Medecin_MEDNO) references Medecin (MEDNO);
alter table Service add constraint FKj27edbyi0t38mttjk3nt0epmh foreign key (dirigePar_MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2b5qxe8kmuwo03ub66t38u7sl foreign key (medecins_MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2elm4l20heoejtp02yy7svmvw foreign key (Service_SERVNO) references Service (SERVNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Medecin_Service (Medecin_MEDNO integer not null, serviceDirige_SERVNO integer not null) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
create table Service_Medecin (Service_SERVNO integer not null, medecins_MEDNO integer not null) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKpepj2nxfefejmp1gchjmqv5l7 foreign key (serviceDirige_SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKb159t3r8h38x92trx1r0jwd9k foreign key (Medecin_MEDNO) references Medecin (MEDNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2b5qxe8kmuwo03ub66t38u7sl foreign key (medecins_MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2elm4l20heoejtp02yy7svmvw foreign key (Service_SERVNO) references Service (SERVNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Medecin_Service (Medecin_MEDNO integer not null, serviceDirige_SERVNO integer not null) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
create table Service_Medecin (Service_SERVNO integer not null, medecins_MEDNO integer not null) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKpepj2nxfefejmp1gchjmqv5l7 foreign key (serviceDirige_SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKb159t3r8h38x92trx1r0jwd9k foreign key (Medecin_MEDNO) references Medecin (MEDNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2b5qxe8kmuwo03ub66t38u7sl foreign key (medecins_MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2elm4l20heoejtp02yy7svmvw foreign key (Service_SERVNO) references Service (SERVNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Medecin_Service (Medecin_MEDNO integer not null, serviceDirige_SERVNO integer not null) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
create table Service_Medecin (Service_SERVNO integer not null, medecins_MEDNO integer not null) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKpepj2nxfefejmp1gchjmqv5l7 foreign key (serviceDirige_SERVNO) references Service (SERVNO);
alter table Medecin_Service add constraint FKb159t3r8h38x92trx1r0jwd9k foreign key (Medecin_MEDNO) references Medecin (MEDNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2b5qxe8kmuwo03ub66t38u7sl foreign key (medecins_MEDNO) references Medecin (MEDNO);
alter table Service_Medecin add constraint FK2elm4l20heoejtp02yy7svmvw foreign key (Service_SERVNO) references Service (SERVNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Medecin (GERANT_ID integer, MEDNO integer not null auto_increment, MEDSALAIRE NUMERIC(10,2) not null, SERVNO integer, MEDNOM varchar(50) not null, MEDPRENOM varchar(50) not null, primary key (MEDNO)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Medecin add constraint UNIQUE_MED unique (MEDNOM, MEDPRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (MEDNO);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (MEDNO);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2) not null, PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2) not null, PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2) not null, PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, ZIP_CODE varchar(255), city varchar(255) not null, street varchar(255) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, ZIP_CODE varchar(255), city varchar(255), street varchar(255), primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Personne (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null auto_increment, SERVNO integer, DTYPE varchar(31) not null, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, ZIP_CODE varchar(255), city varchar(255), street varchar(255), primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Personne add constraint FK2vw24mxpci84u0t728n83ktyg foreign key (GERANT_ID) references Personne (PERSONNE_ID);
alter table Personne add constraint FKe2p08ks68i0q3tet6hymixuqg foreign key (SERVNO) references Service (SERVNO);
alter table Service add constraint FK1wxie4cywhlw5jtjq2wik04tg foreign key (MEDNO) references Personne (PERSONNE_ID);
create table Malade (PERSONNE_ID integer not null, number integer, ZIP_CODE varchar(255), city varchar(255), street varchar(255), primary key (PERSONNE_ID)) engine=InnoDB;
create table Medecin (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null, SERVNO integer, primary key (PERSONNE_ID)) engine=InnoDB;
create table Personne (PERSONNE_ID integer not null auto_increment, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Malade add constraint FKpow4i3y3httr2ko16xs2ajb4e foreign key (PERSONNE_ID) references Personne (PERSONNE_ID);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (PERSONNE_ID);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Medecin add constraint FK40whnv7tmn1q79aegpvwqovc7 foreign key (PERSONNE_ID) references Personne (PERSONNE_ID);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (PERSONNE_ID);
create table Malade (PERSONNE_ID integer not null, number integer, ZIP_CODE varchar(255), city varchar(255), street varchar(255), primary key (PERSONNE_ID)) engine=InnoDB;
create table Medecin (GERANT_ID integer, MEDSALAIRE NUMERIC(10,2), PERSONNE_ID integer not null, SERVNO integer, primary key (PERSONNE_ID)) engine=InnoDB;
create table Personne (PERSONNE_ID integer not null auto_increment, PERSONNE_NOM varchar(50) not null, PERSONNE_PRENOM varchar(50) not null, primary key (PERSONNE_ID)) engine=InnoDB;
create table Service (MEDNO integer, SERVNO integer not null auto_increment, SERVLOC varchar(50) not null, SERVNAME varchar(50) not null, primary key (SERVNO)) engine=InnoDB;
alter table Personne add constraint UNIQUE_PERSONNE unique (PERSONNE_NOM, PERSONNE_PRENOM);
alter table Service add constraint UKavux5vg4fqb798uwlkele6hog unique (SERVNAME);
alter table Malade add constraint FKpow4i3y3httr2ko16xs2ajb4e foreign key (PERSONNE_ID) references Personne (PERSONNE_ID);
alter table Medecin add constraint FKldul0qn6x07kvja07jekwtl8p foreign key (GERANT_ID) references Medecin (PERSONNE_ID);
alter table Medecin add constraint FK8u1uu1gcvvfekrhoccp1soifm foreign key (SERVNO) references Service (SERVNO);
alter table Medecin add constraint FK40whnv7tmn1q79aegpvwqovc7 foreign key (PERSONNE_ID) references Personne (PERSONNE_ID);
alter table Service add constraint FKixnc1rnfwj9olgls58kni6byc foreign key (MEDNO) references Medecin (PERSONNE_ID);
