drop table if exists Service;
drop table if exists Service;
drop table if exists Service;
drop table if exists Service;
drop table if exists Service;
drop table if exists Service;
drop table if exists MEDECIN;
drop table if exists Service;
drop table if exists Medecin;
drop table if exists Service;
drop table if exists Medecin;
drop table if exists Service;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FKmf27fmpdqjkv256vqst0rs1r9;
alter table Medecin_Service drop foreign key FKpepj2nxfefejmp1gchjmqv5l7;
alter table Medecin_Service drop foreign key FKb159t3r8h38x92trx1r0jwd9k;
alter table Service drop foreign key FKj27edbyi0t38mttjk3nt0epmh;
alter table Service_Medecin drop foreign key FK2b5qxe8kmuwo03ub66t38u7sl;
alter table Service_Medecin drop foreign key FK2elm4l20heoejtp02yy7svmvw;
drop table if exists Medecin;
drop table if exists Medecin_Service;
drop table if exists Service;
drop table if exists Service_Medecin;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Medecin_Service drop foreign key FKpepj2nxfefejmp1gchjmqv5l7;
alter table Medecin_Service drop foreign key FKb159t3r8h38x92trx1r0jwd9k;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
alter table Service_Medecin drop foreign key FK2b5qxe8kmuwo03ub66t38u7sl;
alter table Service_Medecin drop foreign key FK2elm4l20heoejtp02yy7svmvw;
drop table if exists Medecin;
drop table if exists Medecin_Service;
drop table if exists Service;
drop table if exists Service_Medecin;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Medecin_Service drop foreign key FKpepj2nxfefejmp1gchjmqv5l7;
alter table Medecin_Service drop foreign key FKb159t3r8h38x92trx1r0jwd9k;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
alter table Service_Medecin drop foreign key FK2b5qxe8kmuwo03ub66t38u7sl;
alter table Service_Medecin drop foreign key FK2elm4l20heoejtp02yy7svmvw;
drop table if exists Medecin;
drop table if exists Medecin_Service;
drop table if exists Service;
drop table if exists Service_Medecin;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Medecin_Service drop foreign key FKpepj2nxfefejmp1gchjmqv5l7;
alter table Medecin_Service drop foreign key FKb159t3r8h38x92trx1r0jwd9k;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
alter table Service_Medecin drop foreign key FK2b5qxe8kmuwo03ub66t38u7sl;
alter table Service_Medecin drop foreign key FK2elm4l20heoejtp02yy7svmvw;
drop table if exists Medecin;
drop table if exists Medecin_Service;
drop table if exists Service;
drop table if exists Service_Medecin;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FKldul0qn6x07kvja07jekwtl8p;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FKldul0qn6x07kvja07jekwtl8p;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FKldul0qn6x07kvja07jekwtl8p;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FKldul0qn6x07kvja07jekwtl8p;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
alter table Medecin drop foreign key FKldul0qn6x07kvja07jekwtl8p;
alter table Medecin drop foreign key FK8u1uu1gcvvfekrhoccp1soifm;
alter table Service drop foreign key FKixnc1rnfwj9olgls58kni6byc;
drop table if exists Medecin;
drop table if exists Service;
